[RDK-29503] Backport latest changes from Sky
rdkcentral/Dobby pull request #25
Opened 2020-08-25 16:27 UTC by TeknoVenus

Port over bugfixes and changes made in Dobby tag 2.0.7.

* Add vpu support
* Add localtime syshook
* Update gpu cgroup support syshook
* Update settings
* Add `AI_TRACE_EVENT` for Perfetto integration
* New build option - `-DENABLE_PERFETTO_TRACING`. Default to off. Requires PerfettoSDK headers installed

Other changes:
* Fix logic issue in `CreateAndStartContainer` to prevent segfault in waitpid
* Bump version number

2020-08-26 09:56 UTC, Anttikyll requested changes

2020-08-26 12:57 UTC, TeknoVenus commented on bundle/lib/source/templates/OciConfigJson1.0.0-rc8.template
>          {{#SYSLOG_SECTION}}{
We only use 1.0.2-dobby, which seems to work fine on all platforms so removed the old unused templates so we just have one to maintain

2020-09-01 09:07 UTC, Anttikyll approved these changes
LGTM

2020-09-03 13:21 UTC, Anttikyll approved these changes
EPG on xi6 launches and plays video fine, with apps working as well.

LGTM.

2020-09-03 13:34 UTC, Anttikyll approved these changes

2020-09-03 13:40 UTC, merged