Port Sky's HttpProxy plugin into an RDK Plugin
rdkcentral/Dobby pull request #52
Opened 2020-09-28 13:24 UTC by anttikyl

### Description

Adds Sky's HttpProxy plugin (legacyPlugin style) as an rdkPlugin.

The HttpProxy plugin adds the ability to add `http_proxy` and `no_proxy` environment variables and proxy CA ceritificates to the container.

Disabled by default. Enabled with cmake flag `-DPLUGIN_HTTPPROXY`

### Test Procedure

To run test:
1. Fill in the `httpproxy` field in the `rdkPlugins` section of a container's config (see `rdkPlugins/HttpProxy/README.md` for instructions).
2. Launch container (make sure `postinstallhooksuccess` is not present)
3. Run `DobbyTool exec [container] cat /etc/ssl/certs/ca-certificates.crt`.

To confirm success:
1. Check that the environment variables are added to the container config as expected in the `process.env` section.
2. Check the container logs to confirm that the `proxyRootCACert` entry was properly prepended at the top of the output of reading `/etc/ssl/certs/ca-certificates.crt`.

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (doesn't fit into the above categories - e.g. documentation updates)

### Requires Bitbake Recipe changes?
- [ ] The base Bitbake recipe (`meta-rdk-ext/recipes-containers/dobby/dobby.bb`) must be modified to support the changes in this PR (beyond updating `SRC_REV`)

2020-09-28 13:47 UTC, mhughesacn commented
I have fixed up the header complaint in the tool and will upvote.
Meantime, I noticed a certificate in the README file - I presume that this is OK for opensourcing?
Thanks,
Martin

2020-09-28 14:09 UTC, anttikyl commented
@mhughesacn 
> Meantime, I noticed a certificate in the README file - I presume that this is OK for opensourcing?

It is only a small portion of a ceritificate, just as an example. I can replace it with something like
 `-----BEGIN CERTIFICATE-----\n[certificate]\n-----END CERTIFICATE-----\n` 
or something similar.

2020-09-28 15:52 UTC, mhughesacn commented
Thanks Antti.  That's fine - I just have to check if I see something like it. - Martin

2020-09-30 14:47 UTC, TeknoVenus requested changes

2020-09-30 14:47 UTC, TeknoVenus commented on rdkPlugins/Networking/README.md
> +"data": {
These changes don't really belong in this PR

2020-09-30 14:47 UTC, TeknoVenus commented on rdkPlugins/Networking/source/NetworkingPlugin.cpp
> -
These changes don't really belong in this PR

2020-09-30 14:47 UTC, TeknoVenus commented on rdkPlugins/HttpProxy/source/HttpProxyPlugin.cpp
> +    snprintf(httpProxyEnvVar, sizeof(httpProxyEnvVar), "httpproxy=http://%s:%d",
This should be `http_proxy`

2020-09-30 14:53 UTC, anttikyl commented on rdkPlugins/HttpProxy/README.md
> +If `ignoreProxyOnBridge` is set to true, the dobby bridge device's address is added to the `no_proxy` environment variable in the container.
The host machine's localhost is accessed via the `dobby0` interface. With this, such traffic will not be proxied.

2020-09-30 15:05 UTC, anttikyl commented on rdkPlugins/HttpProxy/source/HttpProxyPlugin.cpp
> +                         { "bind", "rec", "ro" }))
Good point, I don't think it's needed at all.

2020-09-30 15:06 UTC, TeknoVenus commented on rdkPlugins/HttpProxy/README.md
> +If `ignoreProxyOnBridge` is set to true, the dobby bridge device's address is added to the `no_proxy` environment variable in the container.
Makes sense - thanks! :)

2020-09-30 15:10 UTC, TeknoVenus approved these changes
LGTM

2020-09-30 15:18 UTC, merged